name             'aws-vpc-nat-instance'
maintainer       'Will Salt'
maintainer_email 'will@crowdsurge.com'
license          'Apache 2.0'
description      'Installs/Configures aws-vpc-nat-instance'
long_description 'Installs/Configures aws-vpc-nat-instance'
version          '0.1.0'

depends 'simple_iptables', '= 0.7.1'
depends 'sysctl', '= 0.6.2'